# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:

  - name: Portfolio
    identifier: portfolio
    weight: 2

  - name: Blog
    parent: portfolio
    identifer: certs
    url: "#posts"
    weight: 1

  - name: Certifications
    parent: portfolio
    identifer: certs
    url: "#accomplishments"
    weight: 2

  - name: Contact
    parent: portfolio
    identifier: contact
    url: "#contact"
    weight: 3

  - name: Projects
    parent: portfolio
    identifer: projects
    url: "#projects"
    weight: 4

  - name: Resume
    parent: portfolio
    identifer: resume
    url: uploads/scott_miner_resume.pdf
    weight: 5

  - name: Qualifications
    parent: portfolio
    identifer: qualifications
    url: "#qualifications"
    weight: 6


